from utils import search_similar_questions, user_prompt_to_qna_candidates, insert_qna_cache, get_version, embed_text
from pg import get_connection 
import json


if __name__ == "__main__":
  user_prompts = [
     "주문을 어떻게 접수하나요?",
     "주문 접수 방법",
     "탈퇴 후 다시 회원가입하면 주문 내역은 어떻게 되나요?",
     "회원 탈퇴 후 재가입 시 주문 내역",
  ]
  for user_prompt in user_prompts:
    results = search_similar_questions(user_prompt, top_k=1, threshold=0.15)

    # cache hit 
    for result in enumerate(results):
        idx, (question, answer, section, embedding, distance) = result
        # distance가 0에 가까울수록 유사도가 높음
        print(f"Cache Hit! Similar question found in cache with distance {distance:.4f}")
        print(f"User Prompt: {user_prompt}")
        print(f"Result {idx}: {question} -> {answer} (Distance: {distance:.4f})")
        print("-" * 50)
  

    # cache miss
    if not results:
        print(f"User Prompt: {user_prompt}")
        print("No similar question found in cache.")

        response = user_prompt_to_qna_candidates(user_prompt, reference_docs_path=["../llmwiki/wiki/concepts/*.md"])
        data = json.loads(response.replace('```json', '').replace('```', ''))
        data['qna_candidates'] = data.get('qna_candidates', [])  # qna_candidates 키가 없을 때 빈 리스트로 초기화
        if not data['qna_candidates']:
            print("No QnA candidates generated by LLM.")
            continue
        
        version = get_version("./qna_candidates/")
        qna_list = []
        for qna in data['qna_candidates']:
            source_id = 'user_prompt'
            version = version
            qna_list.append({
                "question": user_prompt,
                "answer": qna["answer"],
                "section": qna.get('section'),
                "embedding": embed_text(qna.get('embedding', '')),
            })
        conn = get_connection()
        insert_qna_cache(
           conn, 
           source_id="user_prompt", 
           version=version, 
           qna_list=qna_list)
        
        print("LLM Response:")
        print(response)
        print("-" * 50)